### ISSUE TITLE
.Net Standard Library Dependency

### ISSUE THREAD

**Issue by ms007** [Domysee/Pather.CSharp#3]
I like your work. 
One thing I noticed is the dependency to the .Net Standard Library. 
When I install the nuget package for Pather.CSharp I end up with over 2000 changed files.

Is the .Net Standard Library really required as a dependency?

**Comment by Domysee** [comment]
Referencing it makes development easier, since I don't have to look for packages to get features that were there by default in "normal" .Net development.
But this shouldn't be an issue, your code should not have to change because of it.
Can you elaborate a bit on what you are doing and why you end up with so many changed files?

**Comment by ms007** [comment]
We do commit our packages directory and the changed files are mainly from the packages directory. 

I've read [here](https://andrewlock.net/what-is-the-netstandard-library-metapackage/) that the NETStandard library package should not be referenced by libraries.

> It's worth noting that the NETStandard.Library package will typically be referenced by projects, though not by libraries.

 but I have to confess that my knowledge about Net Standard is modest and I don't know what the best practices are.

**Comment by Domysee** [comment]
Thanks for that reference.
It seems you are right, I'll change the dependencies in the next version.

**Comment by Domysee** [comment]
This issue is now fixed with version 2.0.4.
Just if anybody is interested, it seems that Microsoft wants to push the NETStandard.Library package. As described in the [csproj reference](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/csproj), the package is implicitly referenced:

> Since `Microsoft.NETCore.App` or `NetStandard.Library` metapackages are implicitly referenced, ...

However, I still agree that referencing as little as possible is the way to go.

It is possible to disable that implicit reference by adding a `DisableImplicitFrameworkReferences` element with `True` as content, as I have now done, but it is not documented in that docs page. 
If found that on a [Stackoverflow question](http://stackoverflow.com/q/42701982/3107430) and then a bit more information on a [ticket](https://github.com/dotnet/sdk/issues/764) on the dotnet sdk.

**Comment by dsplaisted** [comment]
You could disable the NETStandard.Library dependency from being included as a dependency of your NuGet package without disabling the implicit reference entirely with the following:

```xml
<ItemGroup>
    <PackageReference Update="NETStandard.Library" PrivateAssets="true" />
</ItemGroup>
```

This will happen automatically when targeting .NET Standard 2.0 or higher: https://github.com/dotnet/sdk/pull/1171

**Comment by Domysee** [comment]
Thank you, @dsplaisted, this way seems more straightforward.
But is there any difference to using `DisableImplicitFrameworkReferences`?
